openapi: 3.0.0
info:
  title: Meals Management API
  version: 1.0.0
  description: APIs for managing meals, now simplified to plain text payloads.
paths:
  /addMeal:
    post:
      summary: Add a new meal
      description: Add a meal by providing structured JSON parameters.
      operationId: add_meal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                apiPath:
                  type: string
                  example: "/addMeal"
                actionGroup:
                  type: string
                  example: "meals"
                httpMethod:
                  type: string
                  example: "POST"
                parameters:
                  type: object
                  required: [name, calories]
                  properties:
                    name:
                      type: string
                      example: "Chicken Salad"
                    calories:
                      type: number
                      example: 350
                    protein:
                      type: number
                      example: 30
                    carbs:
                      type: number
                      example: 20
                    fat:
                      type: number
                      example: 10
      responses:
        "200":
          description: Meal added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Added Chicken Salad with 350 calories"
  /deleteMeal:
    post:
      summary: Delete a meal
      description: Delete a meal by providing its ID in JSON parameters.
      operationId: delete_meal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                apiPath:
                  type: string
                  example: "/deleteMeal"
                actionGroup:
                  type: string
                  example: "meals"
                httpMethod:
                  type: string
                  example: "POST"
                parameters:
                  type: object
                  required: [meal_id]
                  properties:
                    meal_id:
                      type: integer
                      example: 123
      responses:
        "200":
          description: Meal deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Deleted meal with ID 123"
  /modifyMeal:
    post:
      summary: Modify an existing meal
      description: Modify a meal by providing JSON parameters. `meal_id` is required; other fields are optional.
      operationId: modify_meal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                apiPath:
                  type: string
                  example: "/modifyMeal"
                actionGroup:
                  type: string
                  example: "meals"
                httpMethod:
                  type: string
                  example: "POST"
                parameters:
                  type: object
                  required: [meal_id]
                  properties:
                    meal_id:
                      type: integer
                      example: 123
                    name:
                      type: string
                      example: "Chicken Salad Deluxe"
                    calories:
                      type: number
                      example: 400
                    protein:
                      type: number
                      example: 35
                    carbs:
                      type: number
                      example: 25
                    fat:
                      type: number
                      example: 12
      responses:
        "200":
          description: Meal modified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Modified meal with ID 123"
  /getMeals:
    post:
      summary: Retrieve today's meals
      description: Call this endpoint to get today's meals. Parameters are optional; you can pass an empty parameters object.
      operationId: get_meal
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                apiPath:
                  type: string
                  example: "/getMeals"
                actionGroup:
                  type: string
                  example: "meals"
                httpMethod:
                  type: string
                  example: "POST"
                parameters:
                  type: object
                  properties: {}
      responses:
        "200":
          description: List of today's meals
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: |
                      ID: 123 - Chicken Salad: 350 cal, 30g protein, 20g carbs, 10g fat
                      ID: 124 - Beef Stir Fry: 500 cal, 40g protein, 35g carbs, 20g fat
  /findMealByName:
    post:
      summary: Find meals by fuzzy name matching
      description: Return best matching meals for a provided name. Can optionally perform `modify` or `delete` when confidence is high.
      operationId: find_meal_by_name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                apiPath:
                  type: string
                  example: "/findMealByName"
                actionGroup:
                  type: string
                  example: "meal_tools"
                httpMethod:
                  type: string
                  example: "POST"
                parameters:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
                      example: "burrito"
                    action:
                      type: string
                      enum: ["modify", "delete"]
                      example: "delete"
                    auto_confirm_threshold:
                      type: number
                      example: 0.9
                    calories:
                      type: integer
                      example: 500
                    update_fields:
                      type: object
                      example: {"calories": 450}
      responses:
        "200":
          description: Matching candidates and optional action result
          content:
            application/json:
              schema:
                type: object
                properties:
                  candidates:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        calories:
                          type: number
                        created_at:
                          type: string
                        score:
                          type: number
                  best_match:
                    type: object
                    nullable: true
                  auto_act_performed:
                    type: boolean
                  message:
                    type: string
                    example: "Candidates returned"

