openapi: 3.0.0
info:
  title: Meals Management API
  version: 1.0.0
  description: APIs for managing meals, including adding, deleting, modifying, and retrieving meals for the day.
paths:
  /addMeal:
    post:
      summary: Add a new meal
      description: Add a meal to the daily meal tracker with calories, protein, carbs, and fat.
      operationId: add_meal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the meal
                calories:
                  type: number
                  description: Total calories in the meal
                protein:
                  type: number
                  description: Protein content in grams
                carbs:
                  type: number
                  description: Carbohydrate content in grams
                fat:
                  type: number
                  description: Fat content in grams
              required:
                - name
                - calories
      responses:
        "200":
          description: Meal added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /deleteMeal:
    post:
      summary: Delete a meal
      description: Delete a meal from the daily tracker by its unique ID.
      operationId: delete_meal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                meal_id:
                  type: integer
                  description: Unique ID of the meal to delete
              required:
                - meal_id
      responses:
        "200":
          description: Meal deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /modifyMeal:
    post:
      summary: Modify an existing meal
      description: Update an existing meal's details using its ID.
      operationId: modify_meal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                meal_id:
                  type: integer
                  description: Unique ID of the meal to modify
                name:
                  type: string
                  description: Updated meal name
                calories:
                  type: number
                  description: Updated calories
                protein:
                  type: number
                  description: Updated protein in grams
                carbs:
                  type: number
                  description: Updated carbs in grams
                fat:
                  type: number
                  description: Updated fat in grams
              required:
                - meal_id
      responses:
        "200":
          description: Meal modified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /getMeals:
    post:
      summary: Retrieve today's meals
      description: Get all meals recorded for today.
      operationId: get_meals
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: List of today's meals
          content:
            application/json:
              schema:
                type: object
                properties:
                  meals:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        meal_name:
                          type: string
                        calories:
                          type: number
                        protein:
                          type: number
                        carbs:
                          type: number
                        fat:
                          type: number
                        created_at:
                          type: string
                          format: date-time
