openapi: 3.0.0
info:
  title: Meals Management API
  version: 1.0.0
  description: APIs for managing meals, now simplified to plain text payloads.
paths:
  /addMeal:
    post:
      summary: Add a new meal
      description: Add a meal using a simple text string.
      operationId: add_meal
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: "Chicken Salad, 350 calories, 30g protein, 20g carbs, 10g fat"
      responses:
        "200":
          description: Meal added successfully
          content:
            text/plain:
              schema:
                type: string
                example: "Meal added successfully"
  /deleteMeal:
    post:
      summary: Delete a meal
      description: Delete a meal by providing its ID as text.
      operationId: delete_meal
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: "123"
      responses:
        "200":
          description: Meal deleted successfully
          content:
            text/plain:
              schema:
                type: string
                example: "Meal deleted successfully"
  /modifyMeal:
    post:
      summary: Modify an existing meal
      description: Modify a meal by providing all details in text format.
      operationId: modify_meal
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: "123, Chicken Salad Deluxe, 400 calories, 35g protein, 25g carbs, 12g fat"
      responses:
        "200":
          description: Meal modified successfully
          content:
            text/plain:
              schema:
                type: string
                example: "Meal modified successfully"
  /getMeals:
    post:
      summary: Retrieve today's meals
      description: Simply call this endpoint to get today's meals as a text list.
      operationId: get_meal
      requestBody:
        required: false
        content:
          text/plain:
            schema:
              type: string
              example: ""
      responses:
        "200":
          description: List of today's meals
          content:
            text/plain:
              schema:
                type: string
                example: |
                  123: Chicken Salad, 350 cal, 30g protein
                  124: Beef Stir Fry, 500 cal, 40g protein

